name: Build Windows EXE

on:
  push:
    tags:
      - 'beta-*'   # Se ejecuta solo al subir tags tipo beta-0.1, beta-0.2...
  workflow_dispatch: # Permite lanzarlo manualmente desde GitHub

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        shell: cmd
        run: |
          pyinstaller --onedir --windowed ^
            --icon=resources/icons/SIRA.ico ^
            --name=SIRA ^
            --collect-all jaraco ^
            --collect-all setuptools ^
            --collect-all pkg_resources ^
            --collect-all PySide6 ^
            --collect-all numpy ^
            --collect-all matplotlib ^
            --hidden-import=numpy.core._multiarray_umath ^
            --hidden-import=numpy.core._methods ^
            --exclude-module=tkinter ^
            --add-data "resources;resources" ^
            main.py

      - name: Compress distribution folder
        shell: pwsh
        run: |
          Compress-Archive -Path dist/SIRA/* -DestinationPath dist/SIRA-${{ github.ref_name }}.zip

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: SIRA-${{ github.ref_name }}
          path: dist/SIRA-*.zip

